                                                        NUMPY

In [25]:
import numpy as np
#Ordinary Python Lists
a = [1,2,3,4,5]
print(a[1])
print(a[1:4])
print(a[-1])

#Numpy arrays
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a[1])
print(a[1:])
print(a[:-2])

a_mul = np.array([[[1,2,3,1],[4,5,6,1],[7,8,9,1]],[[1,2,3,1],[4,5,6,1],[7,8,9,1]]])
print(a_mul[0])
print(a_mul[0,1,1])
print(a_mul.shape) #3x3 2d array
print(a_mul.ndim)
print(a_mul.size)
print(a_mul.dtype)

d = {
    '1': 'A'
}

a = np.array(
    [
        [1,d,3],
        [4,"5",6], # if string value was Hello than we would encounter a error because we can not convert it to base int32
        [7,8,9]
    ],dtype='object'
)
print(a.dtype)
print(type(a[1,2]))

2
[2, 3, 4]
5
[1 2 3 4 5]
<class 'numpy.ndarray'>
2
[2 3 4 5]
[1 2 3]
[[1 2 3 1]
 [4 5 6 1]
 [7 8 9 1]]
5
(2, 3, 4)
3
24
int32
object
<class 'int'>
