In [1]:
import cv2

In [2]:
img = cv2.imread('assets/bakircay.png', -1)
#-1, cv2.IMREAD_COLOR = 'Loads a color image any transparency of the image'
#0, cv2.IMREAD_GRAYSCALE = 'Loads image in grayscale mode'
#1, cv2.IMREAD_UNCHANGED = 'Loads image as such including alpha channel'
cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

                                    Image üzerinde oyanama Boyutunu değiştirme döndürme vesayre

In [3]:
img = cv2.resize(img, (0,0), fx=1, fy=1) # (0,0) diyerekten imagin boyunu pixel olarak belirlemiyoruz fx=2 demek imagenin boyunu x ekseninde iki kat arttır demek fy de aynı şekilde y yi iki kat arttıtır
cv2.imshow('Bakircay Logo', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
img = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)

In [5]:
cv2.imwrite('assets/new_img.png', img)

True

                                                  IMAGE MANIPULATION

In [6]:
print(img.shape)

(507, 512, 4)


In [7]:
cv2.imshow('Bakircay',img[50:300][45:400]) # show me the 50th to 450th rows and columns of these row from 45 to 400 we will get the this part of the image
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
import random

for i in range(250) :
    for j in range(img.shape[1]) :
        img[i][j] = [random.randint(0, 255), random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)]
        
cv2.imshow('Bakircay',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
tag = img[100:300, 200:500]
img[0:200, 100:400] = tag
cv2.imshow('Bakircay',img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

                                                Kamera Ile Oynama

                                     SADECE MAVI RENGI ALGILAYIP GOSTEREN KAMERANIN KODU

In [12]:
import numpy as np
cap = cv2.VideoCapture(0) # zero defines which webcam of yours you want to use because i just have one i wrote 0 if i had more than oen webcam i would have written either 1 or 0

while True:
    ret, frame = cap.read()
    width = int(cap.get(3))
    height = int(cap.get(4))
    
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    lower_blue = np.array([90, 50, 0])
    upper_blue = np.array([130, 255, 255])    
    
    mask = cv2.inRange(hsv, lower_blue, upper_blue)
    
    result = cv2.bitwise_and(frame, frame, mask=mask)
    
    cv2.imshow('frame', result)
    cv2.imshow('mask', mask)
    
    if cv2.waitKey(1) == ord('q'):
        break
    
cap.release()
cv2.destroyAllWindows()

                                              EKRANA BİRŞEYLER ÇİZME

In [15]:
import numpy as np
cap = cv2.VideoCapture(0) # zero defines which webcam of yours you want to use because i just have one i wrote 0 if i had more than oen webcam i would have written either 1 or 0
while True:
    ret, frame = cap.read()
    width = int(cap.get(3))
    height = int(cap.get(4))
    
    img = cv2.line(frame, (0,0), (width, height), (255,0,0), 10)
    img = cv2.line(img, (0,height), (width, 0), (0,0,255), 5)
    img = cv2.rectangle(img, (100,100), (200,200), (128,128,128), 3)
    img = cv2.circle(img, (300,300), 60, (0,255,0), -1)
    font = cv2.FONT_HERSHEY_SIMPLEX
    img = cv2.putText(img, 'Cem is great', (10,height-10), font, 2, (0,0,0), 2, cv2.LINE_AA)
    
    cv2.imshow('frame', img)
    
    if cv2.waitKey(1) == ord('q'):
        break
    
cap.release()
cv2.destroyAllWindows()

                                               EKRANI 4`E BOLELIM

In [16]:
import numpy as np
cap = cv2.VideoCapture(0) # zero defines which webcam of yours you want to use because i just have one i wrote 0 if i had more than oen webcam i would have written either 1 or 0
while True:
    ret, frame = cap.read()
    width = int(cap.get(3))
    height = int(cap.get(4))
    
    image = np.zeros(frame.shape, np.uint8)
    smaller_frame = cv2.resize(frame, (0,0), fx=0.5, fy=0.5)
    image[:height//2, :width//2] = cv2.rotate(smaller_frame, cv2.ROTATE_180) #top left
    image[height//2:, :width//2] = smaller_frame # bottom left
    image[:height//2, width//2:] = cv2.rotate(smaller_frame, cv2.ROTATE_180) # top right
    image[height//2:, width//2:] = smaller_frame # bottom right
    cv2.imshow('frame', image)
    
    if cv2.waitKey(1) == ord('q'):
        break
    
cap.release()
cv2.destroyAllWindows()

                                        CORNER DETECTION(Bir Görseldeki Köşeleri Bulan Program)

In [130]:
img = cv2.imread('assets/gamali_hac.png')
img = cv2.resize(img, (0,0), fx=1.25, fy=1.25)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

corners = cv2.goodFeaturesToTrack(gray, 100, 0.1, 10)
corners = np.int0(corners)
print(corners)

for corner in corners :
    x, y = corner.ravel()
    cv2.circle(img, (x,y), 5, (255,0,0), -1)
    
for i in range(len(corners)) :
    for j in range(i+1, len(corners)) :
        corner1 = corners[i][0]
        corner2 = corners[j][0]
        color = tuple(map(lambda x: int(x), np.random.randint(0, 255, size=3)))
        cv2.line(img, corner1, corner2, color, 1)

cv2.imshow('frame', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

C:\Users\Cem\AppData\Local\Temp\ipykernel_23328\4060969853.py:6: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  corners = np.int0(corners)


[[[450 411]]

 [[226 455]]

 [[360 411]]

 [[406 188]]

 [[183 231]]

 [[226 365]]

 [[496 365]]

 [[316 275]]

 [[270 321]]

 [[360 141]]

 [[406 278]]

 [[316 545]]

 [[540 321]]

 [[273 501]]

 [[273 231]]

 [[316 368]]

 [[316  98]]

 [[363 321]]

 [[ 93 321]]

 [[136 278]]]


                            OBJECT DETECTION IN IMAGES(görsellerin içerisinden belirli objeleri seçen yapay zeka)

In [132]:
img = cv2.resize(cv2.imread('assets/soccer_practice.jpg', 0), (0,0), fx=0.8, fy=0.8)
template = cv2.resize(cv2.imread('assets/shoe.PNG', 0), (0,0), fx=0.8, fy=0.8)
h, w = template.shape

methods = [cv2.TM_CCOEFF, cv2.TM_CCOEFF_NORMED, cv2.TM_CCORR,cv2.TM_CCORR_NORMED,cv2.TM_SQDIFF,cv2.TM_SQDIFF_NORMED]

for method in methods:
    img2 = img.copy()
    
    result = cv2.matchTemplate(img2, template, method)
    min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(result)
    if method in [cv2.TM_SQDIFF, cv2.TM_SQDIFF_NORMED] :
        location = min_loc
    else:
        location = max_loc
    
    bottom_right = (location[0] + w, location[1] + h)
    cv2.rectangle(img2, location, bottom_right, 255, 5)
    cv2.imshow('Match', img2)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

                                                        FACE DETECTION

In [133]:
cap = cv2.VideoCapture(0)
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

while True:
    ret, frame = cap.read()
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x,y,w,h) in faces :
        cv2.rectangle(frame, (x,y), (x+w, y+h), (255,0,0), 5)
        roi_gray = gray[y:y+w, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray, 1.3, 5)
        for (ex,ey,ew,eh) in eyes :
            cv2.rectangle(roi_color, (ex,ey), (ex+ew, ey+eh), (0,255,0), 5)
            
    cv2.imshow('frame', frame)
    
    if cv2.waitKey(1) == ord('q') :
        break
    
cap.release()
cv2.destroyAllWindows()